<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class UserRoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $password = '72e82b77';
        $users = [
            // ADMIN
            [
                'name' => 'Admin KPU Cirebon',
                'email' => 'admin@kpu.go.id',
                'nip' => '0000000000000000',
                'jabatan' => 'Administrator',
                'role' => 'admin',
                'phone' => '081200000000',
                'address' => 'Jl. Kantor KPU Cirebon',
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => 'Admin Sistem',
                'department' => 'IT',
                'employee_id' => 'ADMIN001',
                'birth_date' => '1980-01-01',
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            // SEKRETARIS
            [
                'name' => 'ANDARTUA SINAGA, SE., M.Si.',
                'email' => 'sekretaris@kpu.go.id',
                'nip' => '19741152000121001',
                'jabatan' => 'SEKRETARIS',
                'role' => 'sekretaris',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            // KASUBBAG
            [
                'name' => 'NUGRAHA BAMBANG SANTOSO, S.IP',
                'email' => 'kasubbag1@kpu.go.id',
                'nip' => '198610182010121005',
                'jabatan' => 'KASUBBAG KEUANGAN, UMUM DAN LOGISTIK',
                'role' => 'kasubbag',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'ALBET GIUSTI, SE',
                'email' => 'kasubbag2@kpu.go.id',
                'nip' => '198006252010121002',
                'jabatan' => 'KASUBBAG TEGKAR PEMILU DAN HUKUM',
                'role' => 'kasubbag',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'INDAH METHASARI, SE.',
                'email' => 'kasubbag3@kpu.go.id',
                'nip' => '197807152008112001',
                'jabatan' => 'KASUBBAG PERENCANAAN, DATA DAN INFORMASI',
                'role' => 'kasubbag',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'female',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'INTAN SUGIHARTINI, SH., M.Si.',
                'email' => 'kasubbag4@kpu.go.id',
                'nip' => '198512162009122005',
                'jabatan' => 'KASUBBAG PARMAS DAN SUMBER DAYA MANUSIA',
                'role' => 'kasubbag',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'female',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            // STAFF, PPK, PPNPN, dst (berdasarkan struktur organisasi)
            [
                'name' => 'MUHAMMAD OPA MUSTOPA, S.IP.',
                'email' => 'staff1@kpu.go.id',
                'nip' => '198804122019031004',
                'jabatan' => 'FUNGSIONAL UMUM',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'AKHMAD SAEFUL, SE',
                'email' => 'staff2@kpu.go.id',
                'nip' => '197110132009101001',
                'jabatan' => 'FUNGSIONAL UMUM',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'HENDRA GUNAWAN, S.IP.',
                'email' => 'ppk@kpu.go.id',
                'nip' => '199402132019021001',
                'jabatan' => 'FUNGSIONAL UMUM',
                'role' => 'ppk',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'SOLEHUDIN',
                'email' => 'staff3@kpu.go.id',
                'nip' => '197512052009101001',
                'jabatan' => 'FUNGSIONAL UMUM',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'SUHARTONO, S.M',
                'email' => 'staff4@kpu.go.id',
                'nip' => '197804262009101003',
                'jabatan' => 'FUNGSIONAL UMUM',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => 'male',
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'KARYA MULYAWAN',
                'email' => 'staff5@kpu.go.id',
                'nip' => null,
                'jabatan' => 'PPNPN',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'AHMAD SAEFUL',
                'email' => 'staff6@kpu.go.id',
                'nip' => null,
                'jabatan' => 'PPNPN',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'SABAR',
                'email' => 'staff7@kpu.go.id',
                'nip' => null,
                'jabatan' => 'PPNPN',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'RAMADHAN SUPRIYATMAN',
                'email' => 'staff8@kpu.go.id',
                'nip' => null,
                'jabatan' => 'PPNPN',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'NENGSIH SUGIHARTINI, A.Md',
                'email' => 'staff9@kpu.go.id',
                'nip' => null,
                'jabatan' => 'PPNPN',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'DINDIN DEDI JUANDA',
                'email' => 'staff10@kpu.go.id',
                'nip' => null,
                'jabatan' => 'PPNPN',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'FAKHRUROZI',
                'email' => 'staff11@kpu.go.id',
                'nip' => null,
                'jabatan' => 'PPNPN',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'FEBBY FARUL ZAMAN, S.KOM',
                'email' => 'staff12@kpu.go.id',
                'nip' => '198605122024211020',
                'jabatan' => 'PRANATA KOMPUTER',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'SUHARYONO, A.Md.',
                'email' => 'staff13@kpu.go.id',
                'nip' => '197905012023211002',
                'jabatan' => 'ARSIPARIS',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'THOYIB, S.Pd.I',
                'email' => 'staff14@kpu.go.id',
                'nip' => '199103252024211027',
                'jabatan' => 'PENATA KELOLA PEMILU',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'ASEP RUHIAT',
                'email' => 'staff15@kpu.go.id',
                'nip' => null,
                'jabatan' => 'PPNPN',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'TOYIB, SE.',
                'email' => 'staff16@kpu.go.id',
                'nip' => '198012102024211007',
                'jabatan' => 'PENATA KELOLA PEMILU',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
            [
                'name' => 'SUHAIRIN, S.AP.',
                'email' => 'staff17@kpu.go.id',
                'nip' => '197705042024211004',
                'jabatan' => 'PENATA KELOLA PEMILU',
                'role' => 'staff',
                'phone' => null,
                'address' => null,
                'pangkat' => null,
                'golongan' => null,
                'unit_kerja' => 'KPU Kabupaten Cirebon',
                'is_active' => true,
                'email_verified_at' => now(),
                'avatar' => null,
                'bio' => null,
                'department' => null,
                'employee_id' => null,
                'birth_date' => null,
                'gender' => null,
                'password' => $password,
                'remember_token' => Str::random(10),
            ],
        ];
        \App\Models\User::truncate();
        foreach ($users as $user) {
            \App\Models\User::create($user);
        }
        // Seeder dummy SPPD telah dihapus
    }
}
